config/routes.rb
FourWords::Application.routes.draw do

  get "squares/index"

  
  resource :votes
  resource :reports
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/canvas_squares.js' => 'squares#index'
  match '/takeover' => 'squares#takeover'
  match '/free' => 'squares#free', :as => :free
  match '/:action', :controller => 'pages', :as => 'static'
  

  root :to => 'pages#home'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :square
  belongs_to :user
end

app/models/square.rb
class Square < ActiveRecord::Base
  belongs_to :user
  before_save :set_colour, :unset_html
  has_many :votes
  has_many :reports
  
  STD_COLOURS = { :taken => 'FFFFFF', :not_taken => '808285' }
  
  def as_json(options=nil)
    {
      :id => id,
      :h => height,
      :u => user_id,
      :k => html,
      :w => width,
      :x => x,
      :y => y,
      :n => user_id ? user && user.name : nil,
      :d => dailymotion_id
    }
  end
  
  def set_colour
    user_id ? self.colour = STD_COLOURS[:taken] : self.colour = STD_COLOURS[:not_taken]
  end
  
  def unset_html
    self.html = nil unless user_id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :square
  has_many :votes
  has_many :reports
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['user_info']['name']
      user.image_url = auth['user_info']['image']
      user.token = auth['credentials']['token']
    end
  end
  
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :square
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :disclaimer
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def disclaimer
    @disclaimer = true unless request.user_agent =~ /Chrome|Safari/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def about
    @personas = [
      {
        :img => 'ale',
        :name => 'Alessandro Dal Grande',
        :role => 'Web Developer',
        :desc => "His angel face will diddle you. Merciless entity from Hell, sometimes he's struck by a strange energy and becomes  temporarily a kind person that wants to help the most needful. Some say he can see through your webcam by looking at his wristwatch and that he is the inspiration for new fashion trends in Jakarta. All we know, he's called Alessandro.",
        :twitter => 'aledalgrande'
      }, {
        :img => 'ant',
        :name => 'Anthony Wales',
        :role => 'Project Coordinator',
        :desc => "Ant (or Rocco) has a passion for business technology and a creative entrepreneurial spirit. He enjoys managing projects, especially when he can influence the end product! He got a team together to help the 50/50 project because as a husband and father, couldn't imagine what it would be like to not be able to feed your wife let alone your child.",
        :twitter => 'anthonyisrocco'
      }, {
        :img => 'dan',
        :name => 'Daniel Lewis',
        :role => 'Graphic Designer',
        :desc => "Thrives on developing creative solutions to design problems, focused and passionate about illustration, branding, digital and good old pencil skills.\nI'm a keen cook and like travelling the UK for restaurants. \"I'm always prepared to help others and this project was a great opportunity to help make a big difference to the future of East Africa.\"",
        :twitter => 'FrenchieMan'
      }, {
        :img => 'daz',
        :name => 'Darren Pinner',
        :role => 'PR Director',
        :desc => "In the day he masquerades as an MD of a field marketing company and at night he plots his next 'big idea'. Currently working from Bronte Beach, Sydney - it's tough but someone's got to do it.<br/>50/50 offered the opportunity to collaborate with some of the most talented people on the planet to help those on the planet most at need.",
        :twitter => 'Darrenpinner'
      }].shuffle
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  def create
    respond_to do |format|
      format.js do
        if current_user
          square = Square.find_by_dailymotion_id(params[:video_id])
          if !Report.find_by_square_id_and_user_id(square.id, current_user.id)
            current_user.reports.create :square => square
            render :json => 'created'
          else
            render :json => 'found'
          end
        end
      end
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/squares_controller.rb
class SquaresController < ApplicationController

  def index
    render :text => "squares = #{Square.includes(:user).to_json()}"
  end
  
  def takeover
    if current_user
      unless current_user.square
        square = Square.find(params[:square_id])
        if square && square.user_id.nil? && !params[:video_embed_html].blank? && !params[:dailymotion_id].blank?
          current_user.square = square
          square.update_attributes(:html => params[:video_embed_html], :dailymotion_id => params[:dailymotion_id])
          @graph = Koala::Facebook::API.new(current_user.token)
          @graph.put_wall_post("4 Words", {:name => "#{current_user.name} has just adopted a part of East Africa to help save dying children, join the movement at 4 Words", :link => root_url})
        end
      end
    end
    redirect_to root_path
  end
  
  def free
    if current_user
      current_user.square = nil
    end
    redirect_to root_path
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  
  def create
    respond_to do |format|
      format.js do
        if current_user
          square = Square.find_by_dailymotion_id(params[:video_id])
          if !Vote.find_by_square_id_and_user_id(square.id, current_user.id)
            current_user.votes.create :square => square
            render :json => 'created'
          else
            render :json => 'found'
          end
        end
      end
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/squares_helper.rb
module SquaresHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>4 Words - Help For A Change</title>
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Oswald|Poly">
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application", 'raphael' %>
  <%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.jpg' %>
	<meta name="description" property="og:description" content="Get creative with 4 Words to raise awareness for the famine in East Africa!" />
</head>
<body>
	<% if @disclaimer %>
		<div id="disclaimer">
			This browser is not supported, thus the site could have performance problems or do not work at all. Please switch to Chrome or Safari.
		</div>
	<% end %>
	<div id="container">
		<nav>
			<ul>
				<li id="home">
					<%= link_to 'home', '/' %>
				</li>
				<li id="about">
					<%= link_to 'about', '/about' %>
				</li>
					<% if current_user %>
						<li id="session">
							<%= link_to 'Sign Out', signout_path %>
						</li>
						<li id="user">
							<%= image_tag current_user.image_url %>
							<%= current_user.name %>
						</li>
					<% else %>
						<li id="session">
							<%= link_to 'Sign in', '/auth/facebook', :id => 'signin' %>
						</li>
					<% end %>
				<li id="donate">
					<%= link_to 'Donate',  "https://fundraise.unicef.org.uk/Donate/ToEvent/e0d4ef9d-985d-4ea8-9d25-9f480084f22d?project_id=8&return_url=#{root_url}" %>
				</li>
				<li id="social">
					<!-- AddThis Button BEGIN -->
					<div class="addthis_toolbox addthis_default_style addthis_32x32_style" addthis:url="http://4words.co">
						<a class="addthis_button_facebook"></a>
						<a class="addthis_button_twitter"></a>
						<a class="addthis_button_preferred_3"></a>
						<a class="addthis_button_compact"></a>
						<a class="addthis_counter addthis_bubble_style"></a>
					</div>
					<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4e9387bd04058ecc"></script>
					<script type="text/javascript">
						var addthis_share = {
							url: 'http://4words.co',
							description: 'Get creative with 4 Words to raise awareness for the famine in East Africa!',
							templates: {
								twitter: 'Get creative with 4 Words {{url}} via @_4words'
							}
						}
					</script>
					<!-- AddThis Button END -->
				</li>
			</ul>
		</nav>
		<div id="hyu">
			<%= yield %>
		</div>
	</div>
<% if Rails.env.eql? 'production' %>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-26373355-1']);
	  _gaq.push(['_trackPageview']);

	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();

	</script>
<% end %>
</body>
</html>

app/views/pages/about.html.erb
<div class="column centered">
	<div>
		<%= image_tag 'logo.jpg' %>
	</div>
	<div id="information" class="space_above" style="text-align: left;">
		<p style="width: 100%">
			&ldquo;Right now, a child is dying of hunger in Somalia every six minutes. And unless we do something about it, children are going to carry on dying. It’s simple. Children are hungry. We’re not. They have no food. We do. So it's time to share what we have.&rdquo; — UNICEF
		</p>
		
		<h3>
			What Is This?
		</h3>
			
		<p style="width: 100%">
		4 Words is just one (and counting) of 43 web based fundraising projects in 7 countries being created and built by individuals and collectives of people in their spare time – evenings and weekends over the last month as part of the 50/50 collaborative fundraising experiment.
		</p>

		<p style="width: 100%">
			50/50 was first hatched by Good for Nothing and Made by Many about 6 weeks ago with the aim of launching 50 web based fundraising projects in 50 days, ready by World Food Day to try and raise £1M for UNICEF's famine aid in East Africa where a child is dying every 6 minutes from starvation and more than 12 Million people are at risk.
		</p>

		<h3>
			Where’s the money going?
		</h3>

		<p style="width: 100%">
			50/50 have partnered with UNICEF as the official Aid Collection partner. 100% of the money you donate to 4 Words or any of the 50/50 projects goes direct to UNICEF.
		</p>

		<p style="width: 100%">
			Just £5 could provide a child with life-saving food for a week so the potential impact of this collaborative experiment is immense. We hope that the word spreads fast, that the message is shared and that as much money as possible is raised in order for UNICEF to help as many children as possible.
		</p>

		<p style="width: 100%">
			If you have any feedback please drop an email to helpforachange@gmail.com
		</p>
	</div>
	<div id="donate_big">
		<%= link_to 'Donate',  "https://fundraise.unicef.org.uk/Donate/ToEvent/e0d4ef9d-985d-4ea8-9d25-9f480084f22d?project_id=8&return_url=#{root_url}" %>
	</div>
	<div>
		<%= image_tag 'about/map.png' %>
	</div>
</div>

<div class="column">
	<h2>Meet the team</h2>
	<% @personas.each do |persona| %>
		<div class="persona">
			<h3><%= persona[:name] %> ● <%= link_to "@#{persona[:twitter]}", "http://twitter.com/#{persona[:twitter]}", :target => :blank %></h3>
			<h4><%= persona[:role] %></h4>
			<%= image_tag "about/#{persona[:img]}.png" %>
			<p>
				<%= raw persona[:desc] %>
			</p>
		</div>
	<% end %>
</div>

<div class="centered" id="thanks">
	Also thanks for the inputs of: Mariana Moura Santos, Nikolai Lyden and Stefano Belloro.
</div>

app/views/pages/home.html.erb
<% if current_user %>
	<div id="user_id" style="display: none;"><%= current_user.id %></div>
<% end %>

<div id="africa">
	<%= image_tag "mini-africa.png", :title => "mini-africa", :class => "mini-africa" %>
</div>

<div id="introduction">
	<%= image_tag 'logo.jpg' %>
	<h2>
		13 million people in 
		the Horn of Africa are facing a hunger crisis
	</h2>	
	<p>
		Right now, today, children in East Africa are facing a desperate crisis caused by prolonged drought, soaring food prices and conflict. 4 Words hopes to harness your creativity to highlight this crisis to a wider audience.
	</p>
	<h4>
		How you can help
	</h4>
	<p>
		Sign in with your Facebook details ● Adopt your square on the map ● Upload or record your video ● Share it with everyone and anyone<br/>
		You can be as creative as you want with the video you upload making sure to include in some format the 4 words <span class="bold">Help For A Change</span> and that you <%= link_to 'donate',  "https://fundraise.unicef.org.uk/Donate/ToEvent/e0d4ef9d-985d-4ea8-9d25-9f480084f22d?project_id=8&return_url=#{root_url}" %> whatever you can.
	</p>
</div>

<div id="loader">
	<div id="loading">
		Flying to the Horn...
	</div>
</div>

<div id="instructions">
</div>

<script src="http://api.dmcdn.net/all.js"></script>
<script type="text/javascript">
	function canTake() {
		<% if current_user && current_user.square.nil? %>
			return true;
		<% else %>
			return false;
		<% end %>
	}
	function squareText(user_id, user_name) {
		<% if current_user && !current_user.square %>
			if (user_id) {
				return user_name;
			}
			else {
				return 'Adopt square!';
			}
		<% else %>
			if (user_id == '<%= current_user.id if current_user %>')
				return user_name + ' (you!)';
			else if (user_id) {
				return user_name;
			}
			else {
				return 'Not adopted.';
			}
		<% end %>
	}
</script>

<div id="overlay" class="overlay">
	<div class="content">
		<h2>Adopt over your square!</h2>
		<div class="cont">
			<p>To adopt this square you need a video of yourself where the only constraint is you have to include the four words: "Help for a change". The rest is up to you!</p>
			<p>When you have the video you just need to complete 4 steps:</p>
			<ul>
				<li>
					Go to <%= link_to 'Dailymotion', 'http://www.dailymotion.com', :target => :blank %> and login with Facebook<br/>
					<%= image_tag 'signin_dailymotion.png' %>
				</li>
				<li>
					Upload the video or record it from your webcam (remember the 4 words)
				</li>
				<li>
					Go to your Dailymotion profile and copy your username<br/>
					<%= image_tag 'username_dailymotion.png' %><br/>
					in the following field<br/>
					<p><%= text_field_tag 'username' %></p>
				</li>
				<li>
					Click <%= link_to 'Refresh', '#', :id => 'refresh_dailymotion' %> and then on the video you want to link to (it usually takes 10-15 minutes for Dailymotion to publish it)
					<div id="videos">&nbsp;</div>
				</li>
			</ul>
			<%= form_tag '/takeover' do %>
				<%= hidden_field_tag 'video_embed_html' %>
				<%= hidden_field_tag 'dailymotion_id' %>
				<%= hidden_field_tag 'square_id' %>
				<p><%= submit_tag 'Adopt' %></p>
			<% end %>
		</div>
	</div>
</div>

<div id="video_overlay" class="overlay">
	<div id="video_content" class="content">
		<div id="video_id" style="display: none;"></div>
		<h2><span id="author"></span>'s 4 words</h2>
		<div class="cont">
			<div id="video_iframe"></div>
			<div id="video_meta">
				<span id="likes"><%= link_to 'Like ❤', '#', :id => 'like' %></span>
				<span id="score"></span>
				<span id="reports"><%= link_to 'Report ✖', '#', :id => 'report' %></span>
				<span id="views"></span> views
			</div>
			<div id="video_actions"><%= link_to 'Remove', '#', :onclick => "window.location = '#{free_url}'" %></div>
		</div>
	</div>
</div>